package solaire.utility.sql;

public interface SQLCommands {

	String INSERT_EMPLOYEE = "insert into Employee(lastname, firstname, position, department) values(?,?,?,?,?)";
	String GETCPU = "select * from CPU";
	String GETLaptop = "select * from Laptop";
	String GETScan = "select * from Scanners";
	String GETMonitor = "select * from Monitor";
	String GETPrinter = "select * from Printer";
	String GETAccessories = "select * from Accessories";
	String GETService = "select * from ServiceUnit";
	String GETNames = "select * from UnitNames";
	String GETPullOut = "select * from PullOut";
	String GETPutIn = "select * from PutIn";
	String INSERTNames = "insert into UnitNames(Description, Type, IdOther) values(?,?,?)";
	String INSERT_CPU = "insert into CPU(Description, Stocks, PullOut, NumReturn, RemainingItems) values(?,?,?,?,?)";
	String INSERT_Laptop = "insert into Laptop(Description, Stocks, PullOut, NumReturn, RemainingItems) values(?,?,?,?,?)";
	String INSERT_Scan = "insert into Scanners(Description, Stocks, PullOut, NumReturn, RemainingItems) values(?,?,?,?,?)";
	String INSERT_Monitor = "insert into Monitor(Description, Stocks, PullOut, NumReturn, RemainingItems) values(?,?,?,?,?)";
	String INSERT_Printer = "insert into Printer(Description, Stocks, PullOut, NumReturn, RemainingItems) values(?,?,?,?,?)";
	String INSERT_Accessories = "insert into Accessories(Description, Stocks, PullOut, NumReturn, RemainingItems) values(?,?,?,?,?)";
	String INSERT_Service = "insert into ServiceUnit(Description, Stocks, PullOut, NumReturn, RemainingItems) values(?,?,?,?,?)";
	String INSERT_PULL = "insert into PullOut(Date, Tech, Item, Serial, Counts, LOD) values(?,?,?,?,?,?)";
	String INSERT_PUT = "insert into PutIn(Date, Tech, Item, Serial, CompID, Count, Remarks) values(?,?,?,?,?,?,?)";
	String INSERT_Name = "insert into UnitNames(Description, Stocks, PullOut, NumReturn, RemainingItems) values(?,?,?,?,?)";
	String SEARCH_EMPLOYEE = "select * from employee where id=?";
	String UPDATE_EMPLOYEE = "update Employee set lastname = ?, firstname = ?, position=?, department=? where id = ?";
	String SEARCH_ADMIN="Select * from Login where Username=? and Password = ?";
	String SEARCHCPU="Select * from CPU where Description=?";
	String SEARCHLap="Select * from Laptop where Description=?";
	String SEARCHScan="Select * from Scanners where Description=?";
	String SEARCHMoni="Select * from Monitor where Description=?";
	String SEARCHPri="Select * from Printer where Description=?";
	String SEARCHAcc="Select * from Accessories where Description=?";
	String SEARCHServ="Select * from ServiceUnit where Description=?";
	String SPCPU="Select * from CPU where ID=?";
	String SPLap="Select * from Laptop where ID=?";
	String SPScan="Select * from Scanners where ID=?";
	String SPMoni="Select * from Monitor where ID=?";
	String SPPri="Select * from Printer where ID=?";
	String SPAcc="Select * from Accessories where ID=?";
	String SPServ="Select * from ServiceUnit where ID=?";
	String DELETE_EMPLOYEE = "delete from employee where id=?";
	String PULLCPU="update CPU set PullOut = ?, RemainingItems = ? where ID = ?";
	String PULLMoni="update Monitor set PullOut = ?, RemainingItems = ? where ID = ?";
	String PULLPrin="update Printer set PullOut = ?, RemainingItems = ? where ID = ?";
	String PULLSca="update Scanners set PullOut = ?, RemainingItems = ? where ID = ?";
	String PULLAcs="update Accessories set PullOut = ?, RemainingItems = ? where ID = ?";
	String PULLLap="update Laptop set PullOut = ?, RemainingItems = ? where ID = ?";
	String PULLSU="update ServiceUnit set PullOut = ?, RemainingItems = ? where ID = ?";
	String PUTCPU="update CPU set NumReturn = ?, RemainingItems = ? where ID = ?";
	String PUTMoni="update Monitor set NumReturn = ?, RemainingItems = ? where ID = ?";
	String PUTPrin="update Printer set NumReturn = ?, RemainingItems = ? where ID = ?";
	String PUTSca="update Scanners set NumReturn = ?, RemainingItems = ? where ID = ?";
	String PUTAcs="update Accessories set NumReturn = ?, RemainingItems = ? where ID = ?";
	String PUTLap="update Laptop set NumReturn = ?, RemainingItems = ? where ID = ?";
	String PUTSU="update ServiceUnit set NumReturn = ?, RemainingItems = ? where ID = ?";
}
